name: Gráfico de contribuições

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Gerar animação do gráfico de contribuições
        uses: Platane/snk/svg-only@main
        with:
          github_user_name: franklin-albuquerque
          outputs: |
            - name: Animação (tema claro)
              dist/github-contribution-grid-snake.svg
            - name: Animação (tema escuro)
              dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Enviar animações para a branch output
        uses: crazy-max/ghaction-github-pages@dev
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
